# Generated by Django 3.2.7 on 2021-09-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('image', models.CharField(max_length=500)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('interests', models.CharField(max_length=300)),
                ('catnip', models.BooleanField()),
                ('liked_users', models.IntegerField()),
                ('liked_by', models.IntegerField()),
            ],
        ),
    ]
