# Generated by Django 3.2.7 on 2021-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floppas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_by',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_users',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
