# Generated by Django 3.2.7 on 2021-09-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floppas', '0002_auto_20210909_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='liked_by',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='liked_users',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
